# Generated by Django 5.0.4 on 2025-04-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="avatar_hash",
            new_name="avatar",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="display_name",
            new_name="global_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
