# Generated by Django 5.0.4 on 2025-04-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_avatar_hash_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="discord_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
