# Generated by Django 5.0.4 on 2025-04-09 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_discord_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weapon_type", models.CharField(max_length=50)),
                ("attack_power", models.IntegerField(default=0)),
                ("durability", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(default=0)),
                ("defense", models.IntegerField(default=0)),
                ("range", models.IntegerField(default=0)),
                ("speed", models.IntegerField(default=0)),
                ("critical_damage", models.FloatField(default=1.5)),
                ("critical_hit_chance", models.FloatField(default=0.05)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=50)),
                ("level", models.IntegerField(default=0)),
                ("cooldown", models.IntegerField(default=0)),
                ("current_cooldown", models.IntegerField(default=0)),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="accounts.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inheritance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_stat_increase", models.IntegerField(default=0)),
                ("additional_enhance", models.JSONField(default=dict)),
                ("inheritance_level", models.IntegerField(default=0)),
                ("inheritance_date", models.DateTimeField(auto_now_add=True)),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inheritances",
                        to="accounts.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enhancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attack_enhance", models.IntegerField(default=0)),
                ("durability_enhance", models.IntegerField(default=0)),
                ("accuracy_enhance", models.IntegerField(default=0)),
                ("speed_enhance", models.IntegerField(default=0)),
                ("enhancement_level", models.IntegerField(default=0)),
                ("enhancement_date", models.DateTimeField(auto_now_add=True)),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enhancements",
                        to="accounts.weapon",
                    ),
                ),
            ],
        ),
    ]
