# Generated by Django 5.0.4 on 2025-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_weapon_skill_inheritance_enhancement"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="skill_enhance",
            field=models.IntegerField(default=0),
        ),
    ]
