# Generated by Django 5.0.4 on 2025-04-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_accuracy_weapon_base_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inheritance",
            name="base_skill_level_increase",
            field=models.IntegerField(default=0),
        ),
    ]
