# Generated by Django 5.0.4 on 2025-04-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_inheritance_base_skill_level_increase"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancement",
            name="balance_enhance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enhancement",
            name="critical_damage_enhance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enhancement",
            name="critical_hit_chance_enhance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enhancement",
            name="defense_enhance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enhancement",
            name="skill_enhance",
            field=models.IntegerField(default=0),
        ),
    ]
