# Generated by Django 5.0.4 on 2025-04-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_enhancement_balance_enhance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_description",
            field=models.TextField(default="설명이 없습니다"),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
