# Generated by Django 5.0.4 on 2025-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_skill_skill_description_skill_skill_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="skill_notes",
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_notes_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_notes_params",
            field=models.JSONField(default=dict),
        ),
    ]
