# Generated by Django 5.0.4 on 2025-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_skill_skill_notes_skill_skill_notes_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="range",
            field=models.IntegerField(default=0),
        ),
    ]
