# Generated by Django 5.0.4 on 2025-04-11 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_skill_range"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="range",
            new_name="skill_range",
        ),
    ]
