# Generated by Django 5.0.4 on 2025-06-13 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_rename_range_skill_skill_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="skill_range",
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="base_range",
        ),
        migrations.AlterField(
            model_name="weapon",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
